### ISSUE TITLE
Identify false positives

### ISSUE THREAD

**Issue by robsavoye** [hotosm/osm-merge#5]
ML/AI building footprints often flag shapes that aren't buildings at all. The footprint in question can be compared to nearby features in an OSM database to guess the probability the footprint is a buildings. Any feature identified as such get a unique tag added so they can be easily found using JOSM for manual validation.

**Comment by robsavoye** [comment]
Current validation looks good, so any more false positives are a bug, and not an enhancement.

**Comment by rsavoye** [comment]
way out of date.
